### ISSUE TITLE
Problems with the endpoint in GetOrder method  

### ISSUE THREAD

**Issue by FranciscoAmo** [guibranco/VTEX-SDK-dotnet#70]
I want to get the getOrders orders from a vtex store and the lib returns an error because the internal getOrder endpoint is `https://{{accountName}}.myvtex.com.vtexcommercestable.com.br/api/oms/pvt/orders`.
 
In my case if I point via POSTMAN to `https://{{accountName}}.myvtex.com/api/oms/pvt/orders` it returns them correctly. 

Your private method ServiceInvokerAsync has a parameter for the endpoint and a switch to select them. 
I see that the requests method uses the default value and in my case I need the RequestEndpoint.BRIDGE point. but it is read only. 

Thanks for your time

**Comment by guibranco** [comment]
@FranciscoAmo thanks for the report, I'll work to fix it!

**Comment by guibranco** [comment]
@FranciscoAmo did you pass only the `accountName` instead `accountName.myvtex.com` to the constructor method ?

**Comment by guibranco** [comment]
@FranciscoAmo More than a year ago you reported this issue, but I didn't hear back from you about it until now I guess you figured out what to do about or fix it so I will close this thread. Feel free to reopen or submit a new issue if you have any other problem related to this library.
